name: Specs

on: 
 pull_request:
   types: [opened, synchronize, reopened]
 push:
   branches:
     - master


jobs:
  docker:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.0', '3.1', '3.2', '3.3']
        registry-version: ['v1', 'v2']
    steps:
    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Checkout
      uses: actions/checkout@v1

    - name: bundle install
      run: bundle install
    
    - name: Run specs
      run: rspec
